root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  bin = "tmp/main"
  include_ext = ["go", "html", "env"]
  exclude_dir = ["tmp", "vendor"]
  delay = 1000
  stop_on_error = true

[log]
  time = true
