root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ./cmd/main.go"
  bin = "tmp/main.exe"
  include_ext = ["go", "html", "env"]
  exclude_dir = ["tmp", "vendor"]

[log]
  time = true

[dev]
  cmd = "tmp/main.exe"
  include_env = [".env"]
